Update pre_job_per_branch.yml

diff --git a/.github/workflows/pre_job_per_branch.yml b/.github/workflows/pre_job_per_branch.yml
--- a/.github/workflows/pre_job_per_branch.yml
+++ b/.github/workflows/pre_job_per_branch.yml
@@ -272,66 +272,87 @@ jobs:
         id: singularity
         if: ${{contains(fromJson('["true", true]'), steps.set_defaults.outputs.enable_singularity) }}
         run: |
-          docker_file=$(ls [Dd]ocker[Ff]ile)
-          req_file=$(ls requirements.txt)
+          if [ "${{ steps.set_defaults.outputs.default_singularity }}" = "false" ] then
+            SING=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.remote_user }}@${{ secrets.remote_host }}"  \
+            "cd ${{vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH}} && ls -d ${{steps.set_defaults.outputs.singularity}}*" | head -n 1 || true)
+            
+            if [ -z "$SING" ] && ; then
+                echo "Error: Singularity image does not exist and enable_singularity is set to true. Please check the name of singularity"
+                exit 1
+            fi
+          else
           
-          docker_sha=$(md5sum "$docker_file" | awk '{print $1}')
-          req_sha=$(md5sum "$req_file" | awk '{print $1}')
-          
-          docker_sha=${docker_sha:-null}
-          req_sha=${req_sha:-null}
-
-          OLD_SING=null
-
-          
-          SING=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.remote_user }}@${{ secrets.remote_host }}" 2>/dev/null \
-          "cd ${{vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH}} && ls -d ${{steps.set_defaults.outputs.singularity}}:docker_${docker_sha}-req_${req_sha}*" | head -n 1 || true)
-          
-          if [ -z "$SING" ]; then
+            # Check if Dockerfile exists
+            if ls [Dd]ocker[Ff]ile 1>/dev/null 2>&1; then
+                docker_file=$(ls [Dd]ocker[Ff]ile)
+                docker_sha=$(md5sum "$docker_file" | awk '{print $1}')
+            else
+                echo "Error: Dockerfile does not exist."
+                exit 1
+            fi
+            
+            # Check if requirements.txt exists
+            if ls requirements.txt 1>/dev/null 2>&1; then
+                req_file=$(ls requirements.txt)
+                req_sha=$(md5sum "$req_file" | awk '{print $1}')
+            else
+                echo "Warning: requirements.txt does not exist, you can add to install libraries apart."
+            fi
+            
+            docker_sha=${docker_sha:-null}
+            req_sha=${req_sha:-null}
+  
+            OLD_SING=null
             
             SING=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.remote_user }}@${{ secrets.remote_host }}" 2>/dev/null \
-                      "cd ${{vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH}} && ls -dt ${{steps.set_defaults.outputs.singularity}}*" | head -n 1 || true)
+            "cd ${{vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH}} && ls -d ${{steps.set_defaults.outputs.singularity}}:docker_${docker_sha}-req_${req_sha}*" | head -n 1 || true)
             
-            if [ '${{steps.set_defaults.outputs.default_singularity}}' = 'true' ]; then
-              if [ -z "$SING" ]; then
-                [ "$docker_sha" = "null" ] && echo "Please add docker file as [Dockerfile, DockerFile, dockerFile, dockerfile] or disable singularity in your config.yml" && exit 1
-                echo "create_singularity=true" >> $GITHUB_OUTPUT
-                echo "install_reqs=true" >> $GITHUB_OUTPUT
-                OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null${{steps.set_defaults.outputs.sif}}
-
-              else
-                old_docker_sha=$(echo "$SING" | awk -F'docker_' '{print $2}' | awk -F'-req' '{print $1}')
-                old_req_sha=$(echo "$SING" | awk -F'req_' '{print $2}')
-                old_req_sha=${old_req_sha%.sif}
-                
-                if [ "$docker_sha" = "null" ]; then
-                    echo "create_singularity=false" >> $GITHUB_OUTPUT
-                    docker_sha="$old_docker_sha"
-                elif [ "$docker_sha" != "$old_docker_sha" ]; then
-                    CREATE=true
-                    echo "create_singularity=true" >> $GITHUB_OUTPUT
-                fi
-                
-                if [ "$req_sha" = "null" ]; then
-                    echo "install_reqs=false" >> $GITHUB_OUTPUT
-                    req_sha="$old_req_sha"
-                elif [ "$req_sha" != "$old_req_sha" ]; then
-                    if [ "$CREATE" = "true" ]; then #On build it will put req sha to null
-                      OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null${{steps.set_defaults.outputs.sif}}
-                    else
-                      OLD_SING=$SING
-                    fi
-                    echo "install_reqs=true" >> $GITHUB_OUTPUT
-                elif [ "$CREATE" = "true" ]; then
-                  OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null
+            if [ -z "$SING" ]; then
+              
+              SING=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.remote_user }}@${{ secrets.remote_host }}" 2>/dev/null \
+                        "cd ${{vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH}} && ls -dt ${{steps.set_defaults.outputs.singularity}}*" | head -n 1 || true)
+              
+              if [ '${{steps.set_defaults.outputs.default_singularity}}' = 'true' ]; then
+                if [ -z "$SING" ]; then
+                  [ "$docker_sha" = "null" ] && echo "Please add docker file as [Dockerfile, DockerFile, dockerFile, dockerfile] or disable singularity in your config.yml" && exit 1
+                  echo "create_singularity=true" >> $GITHUB_OUTPUT
                   echo "install_reqs=true" >> $GITHUB_OUTPUT
+                  OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null${{steps.set_defaults.outputs.sif}}
+  
+                else
+                  old_docker_sha=$(echo "$SING" | awk -F'docker_' '{print $2}' | awk -F'-req' '{print $1}')
+                  old_req_sha=$(echo "$SING" | awk -F'req_' '{print $2}')
+                  old_req_sha=${old_req_sha%.sif}
+                  
+                  if [ "$docker_sha" = "null" ]; then
+                      echo "create_singularity=false" >> $GITHUB_OUTPUT
+                      docker_sha="$old_docker_sha"
+                  elif [ "$docker_sha" != "$old_docker_sha" ]; then
+                      CREATE=true
+                      echo "create_singularity=true" >> $GITHUB_OUTPUT
+                  fi
+                  
+                  if [ "$req_sha" = "null" ]; then
+                      echo "install_reqs=false" >> $GITHUB_OUTPUT
+                      req_sha="$old_req_sha"
+                  elif [ "$req_sha" != "$old_req_sha" ]; then
+                      if [ "$CREATE" = "true" ]; then #On build it will put req sha to null
+                        OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null${{steps.set_defaults.outputs.sif}}
+                      else
+                        OLD_SING=$SING
+                      fi
+                      echo "install_reqs=true" >> $GITHUB_OUTPUT
+                  elif [ "$CREATE" = "true" ]; then
+                    OLD_SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_null
+                    echo "install_reqs=true" >> $GITHUB_OUTPUT
+                  fi
                 fi
-              fi
-              if [[ $OLD_SING == *.sif ]]; then
-                SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_${req_sha}${{steps.set_defaults.outputs.sif}}
-              else
-              SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_${req_sha}
-
+                if [[ $OLD_SING == *.sif ]]; then
+                  SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_${req_sha}${{steps.set_defaults.outputs.sif}}
+                else
+                SING=${{steps.set_defaults.outputs.singularity}}.docker_${docker_sha}-req_${req_sha}
+  
+                fi
               fi
             fi
           fi
